application: mymarks
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /add\_subject\.html
  static_files: add_subject.html
  upload: add\_subject\.html
  application_readable: True

- url: /resources
  static_dir: resources

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"